add_newline = false


format = """
$env_var\
$username\
$directory\
$git_branch\
$character
"""

[username]
style_user = "green bold"
style_root = "green bold"
format = "[$user]($style)@ "
disabled = false
show_always = true

[directory]
style = "#fa7d09 bold"

[env_var]
variable = "VIRTUAL_ENV"
style = "bright-white dimmed"
format = "\\(env\\) "
